#define _POSIX_C_SOURCE 200809L

#include "chroma-wayland-support.h"

#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <unistd.h>

ssize_t chroma_write_no_sigpipe(int fd, const void *buffer, size_t count) {
  sigset_t blocked;
  sigset_t previous;
  sigemptyset(&blocked);
  sigaddset(&blocked, SIGPIPE);

  int mask_result = pthread_sigmask(SIG_BLOCK, &blocked, &previous);
  if (mask_result != 0) {
    errno = mask_result;
    return -1;
  }

  sigset_t pending;
  int was_pending = sigpending(&pending) == 0 && sigismember(&pending, SIGPIPE);
  ssize_t result = write(fd, buffer, count);

  /* Consume only a SIGPIPE generated by this write. Leaving it pending before
     restoring the caller's mask could deliver it immediately. */
  if (result < 0 && errno == EPIPE && !was_pending) {
    int consumed_signal;
    while (sigwait(&blocked, &consumed_signal) == EINTR) {}
    errno = EPIPE;
  }

  int saved_errno = errno;
  pthread_sigmask(SIG_SETMASK, &previous, NULL);
  errno = saved_errno;
  return result;
}
