#define _POSIX_C_SOURCE 200809L

#include "chroma-wayland-support.h"

#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <unistd.h>

ssize_t chroma_write_no_sigpipe(int fd, const void *buffer, size_t count) {
  sigset_t blocked;
  sigset_t previous;
  sigemptyset(&blocked);
  sigaddset(&blocked, SIGPIPE);

  int mask_result = pthread_sigmask(SIG_BLOCK, &blocked, &previous);
  if (mask_result != 0) {
    errno = mask_result;
    return -1;
  }

  sigset_t pending;
  int was_pending = sigpending(&pending) == 0 && sigismember(&pending, SIGPIPE);
  ssize_t result = write(fd, buffer, count);
  int saved_errno = errno;

  /* Consume only a SIGPIPE generated by this write. An ignored SIGPIPE is not
     made pending, so verify that one exists before waiting for it. */
  if (result < 0 && saved_errno == EPIPE && !was_pending &&
      sigpending(&pending) == 0 && sigismember(&pending, SIGPIPE)) {
    int consumed_signal;
    (void)sigwait(&blocked, &consumed_signal);
  }

  pthread_sigmask(SIG_SETMASK, &previous, NULL);
  errno = saved_errno;
  return result;
}
